### PR TITLE
Use new Remotes devtools feature to install remote dependencies

### PR DESCRIPTION
**Pull request by jimhester**
See https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd for details

### CODE REVIEW

**Comment by hadley** [comment]
Maybe needs note about devtools version in readme?

**Comment by jimhester** [comment]
Yes I will add that,

I think it is failing on Travis because the devtools version in the ppa is not updated yet, looking into it.

**Comment by hadley** [comment]
This will still fail on travis, right? (because of the devtools buglet?)

**Comment by jimhester** [comment]
https://github.com/jimhester/ggplot2-book/commit/2b14ce101616b9bae6ddd1c377cc6afd84052717 worked as far as the Remotes were concerned (as it installs the development version of devtools first). The build failed for what looks to me like an unrelated reason. (https://travis-ci.org/hadley/ggplot2-book/builds/83950259#L2528-L2529)

**Comment by hadley** [comment]
Ok, got it - thanks!

**Pull request merged**
