### PR TITLE
Scales chapter

### PR DESCRIPTION
**Pull request by djnavarro**
First pass at the new scales chapter. The overall structure:

- The early sections are roughly the same: introduction then scale limits 
- Scale-specific sections are organised by aesthetic (position, colour, size, other) and then subdivided by fundamental type (continuous, discrete, binned)
- Transformations move to the end, making it easier to show transformations of non-position scales

Possible concerns:
 
- I *think* the merge conflicts are minor things, and hopefully remain so even after the guides PR is merged?
- Unsuprisingly, the colour scale section is long: there are so many continuous colour scales that I've subdivided (again!) into the general purpose scales (gradient, gradient2, gradientn) and the hand-picked palette scales (brewer/distiller, scico, paletteer). I think it works, but I don't love the fact that there are now level 4 headings.
- I still think there should be a section on transformations of binned scales, but at the moment I'm having troubles getting it to work. Either there is a bug, some unexpected behaviour, or I'm misunderstanding something. What I originally had in mind was to use binned scale transformations as an excuse to show how to define a novel transformation with the scales package, but obviously that's on hold while I figure out what's going on!
- My usual placeholder worry... I don't know what I don't know, so maybe I'm missing something important :upside_down_face: 

Other notes:

- There's a couple of places where the line length is suspiciously long (i.e., more than 80 chars). They do fit on one line when the book is rendered, but it's something I want to think about. Visually I don't want to break those cases over multiple lines if I can avoid it. 

In any case, I think it's reached the point where a review would help! :slightly_smiling_face:

### CODE REVIEW

**Comment by hadley** [comment]
How are you creating the initial branches? I think something in your early workflow is causing excessive work later on.

**Comment by djnavarro** [comment]
Extremely amateurishly! 😁

The workflow I'm trying to shift to is to use `pr_pull_upstream()` to update master on my fork and then `pr_init()` to create the branch. Is that the best way do do this?

Suffice it to say I did not do a particularly good job of it in this case. Partly the usual errors of inexperience, but partly a consequence of my own thinking about the scales + guides chapters having been muddled for a while! 🙂

**Comment by hadley** [comment]
Ah, it looks like something might be messed up in your master branch — it's probably something you did a long time ago that is now making life difficult. At the next logical point, I'd recommend burning it all down and starting again with `create_from_github()` which should set up everything in a way less likely to cause problems down the road.

**Comment by hadley** [comment]
A bunch of comments inline 😄

**Comment by djnavarro** [comment]
Hi @hadley -- 

Modest changes in this iteration:

- convenience functions `xlim()`, `ylim()` and `lims()` appear organically as part of a "setting multiple limits" section which discusses how to keep scales consistent across plots
- there is now an example illustrating the difference between `ylim()` and `coord_cartesian()` using boxplots to illustrate that out of bound values are removed prior to computing the stat
- there's an attempt (not entirely successful, I think, but I'll revisit) at reordering the colour scales sections so that the hand-picked scales appear before the general-purpose ones
- the extra inline comments are just promissory notes; reminders to revisit those points when I try to restructure these chapters into a "scales toolbox". 

At this point I'm tempted to merge these changes into master and start a brand new PR that attempts the restructure?

I _suppose_ now that I'm a collaborator I could do this myself (I'm guessing squash and merge would be the appropriate way to add this). I think I've gotten comfortable enough with the process to be able to manage it, but wanted to check before I start meddling with the master branch :grin:

**Comment by hadley** [comment]
Yeah, I think you should do it! I think the main thing to remember is that after you've clicked "squash and merge" you should run `pr_finish()` in your local branch; that takes care of cleaning everything up locally.

**Pull request merged**
