### PR TITLE
Fix missing Hmisc dependency for plots using `ggplot2::mean_cl_normal()`

### PR DESCRIPTION
**Pull request by dgromer**
Fixes https://github.com/hadley/ggplot2-book/issues/276

### CODE REVIEW

**Comment by hadley** [comment]
Can you please put the package in `DESCRIPTION`?

**Comment by dgromer** [comment]
I have created a PR for ggplot2: https://github.com/tidyverse/ggplot2/pull/4625. With this fix in place, you can close this PR as it is unneccesary then.

**Comment by yutannihilation** [comment]
I guess it's [the `DESCRIPTION` of this repo](https://github.com/hadley/ggplot2-book/blob/master/DESCRIPTION), not ggplot2's one.

**Comment by dgromer** [comment]
I was not aware that the book has a DESCRIPTION file ;)

See https://github.com/hadley/ggplot2-book/pull/278

**Pull request closed without merging**
