### PR TITLE
Fix: Rectify build status badge

### PR DESCRIPTION
**Pull request by Abinashbunty**
Rendered the build status badge correctly by referencing the correct path

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind keeping it linked to the results of the action?

**Comment by Abinashbunty** [comment]
I used the docs from [Using `event` parameter](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-event-parameter) to modify the build status badge.

**Comment by hadley** [comment]
Apologies for not being clear — previously, you could click on the badge to go to the results of the actions, but your change removed the link. Could you please re-add it?

**Comment by Abinashbunty** [comment]
Ah alright. Now it's fixed. 😄

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
