### PR TITLE
Scales and guides

### PR DESCRIPTION
**Pull request by djnavarro**
Purely a convenience. Assuming I have not made a mistake this PR:

- fixes the merge conflict on DESCRIPTION file with master
- subsumes and closes #192 
- subsumes and closes #194

### CODE REVIEW

**Comment by hadley** [comment]
Do you want me to merge this one and close the other two? (Just confirming I understand your goal here)

**Comment by djnavarro** [comment]
Yep!

**Comment by hadley** [comment]
I think it would be a bit simpler to merge the guides PR, then review and merge the scales PR. I'm happy to resolve the merge conflicts and then push back into your branch.

**Comment by djnavarro** [comment]
sounds totally fine!

**Pull request closed without merging**
