### PR TITLE
"tibble" to "sf" transformation simplified

### PR DESCRIPTION
**Pull request by xiaochi-liu**

### CODE REVIEW

**Comment by hadley** [comment]
@djnavarro and this one too please?

**Comment by xiaochi-liu** [comment]
Sorry, I should put the running result too.

``` r
library(tidyverse)
library(sf)
#> Linking to GEOS 3.7.2, GDAL 2.4.2, PROJ 5.2.0
oz_capitals <- tibble::tribble( 
  ~city,           ~lat,     ~lon,
  "Sydney",    -33.8688, 151.2093,  
  "Melbourne", -37.8136, 144.9631, 
  "Brisbane",  -27.4698, 153.0251, 
  "Adelaide",  -34.9285, 138.6007, 
  "Perth",     -31.9505, 115.8605, 
  "Hobart",    -42.8821, 147.3272, 
  "Canberra",  -35.2809, 149.1300, 
  "Darwin",    -12.4634, 130.8456, 
)

oz_capitals
#> # A tibble: 8 x 3
#>   city        lat   lon
#>   <chr>     <dbl> <dbl>
#> 1 Sydney    -33.9  151.
#> 2 Melbourne -37.8  145.
#> 3 Brisbane  -27.5  153.
#> 4 Adelaide  -34.9  139.
#> 5 Perth     -32.0  116.
#> 6 Hobart    -42.9  147.
#> 7 Canberra  -35.3  149.
#> 8 Darwin    -12.5  131.

cities <- st_as_sf(oz_capitals,
                   coords = c("lon", "lat"), 
                   crs = 4326, 
                   remove = FALSE)

cities
#> Simple feature collection with 8 features and 3 fields
#> geometry type:  POINT
#> dimension:      XY
#> bbox:           xmin: 115.8605 ymin: -42.8821 xmax: 153.0251 ymax: -12.4634
#> CRS:            EPSG:4326
#> # A tibble: 8 x 4
#>   city        lat   lon            geometry
#> * <chr>     <dbl> <dbl>         <POINT [°]>
#> 1 Sydney    -33.9  151. (151.2093 -33.8688)
#> 2 Melbourne -37.8  145. (144.9631 -37.8136)
#> 3 Brisbane  -27.5  153. (153.0251 -27.4698)
#> 4 Adelaide  -34.9  139. (138.6007 -34.9285)
#> 5 Perth     -32.0  116. (115.8605 -31.9505)
#> 6 Hobart    -42.9  147. (147.3272 -42.8821)
#> 7 Canberra  -35.3  149.   (149.13 -35.2809)
#> 8 Darwin    -12.5  131. (130.8456 -12.4634)
```

<sup>Created on 2020-11-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by djnavarro** [comment]
This is really nice! I think I'll take it a step further and remove my version entirely. Your version with `st_as_sf()` is cleaner than my original code, and I think the chapter would benefit from the more streamlined exposition. Thank you!

**Comment by xiaochi-liu** [comment]
Thanks @djnavarro. Glad to be helpful.

**Pull request merged**
